name: 'finance_data_platform'
version: '1.0.0'
config-version: 2

profile: 'finance_data_platform'

model-paths: ["models"]
test-paths:  ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  finance_data_platform:
    bronze:
      +schema:            bronze
      +materialized:      incremental
      +incremental_strategy: append
      +on_schema_change:  append_new_columns
      +tags:              ['bronze']

    silver:
      +schema:            silver
      +materialized:      incremental
      +incremental_strategy: merge
      +on_schema_change:  sync_all_columns
      +tags:              ['silver']

    gold:
      +schema:            gold
      +materialized:      table
      +tags:              ['gold']

      dimensions:
        +materialized:    table

      facts:
        +materialized:    incremental
        +incremental_strategy: merge
        +on_schema_change: sync_all_columns

vars:
  start_date:           '2020-01-01'
  target_currency:      'USD'
  fiscal_year_start_month: 7   # July — fiscal year July-June
