-- ============================================================
-- FINANCE DATA PLATFORM — SNOWFLAKE SETUP
-- Script 01: Schemas, Warehouses, Roles, Grants
-- Run this as ACCOUNTADMIN
-- ============================================================

USE ROLE ACCOUNTADMIN;

-- ────────────────────────────────────────
-- DATABASE
-- ────────────────────────────────────────
CREATE DATABASE IF NOT EXISTS FINANCE_PLATFORM_DEV
    COMMENT = 'Enterprise Finance Data Platform — Dev Environment';

USE DATABASE FINANCE_PLATFORM_DEV;

-- ────────────────────────────────────────
-- SCHEMAS
-- ────────────────────────────────────────
CREATE SCHEMA IF NOT EXISTS RAW
    COMMENT = 'Raw staged data loaded directly from ADLS via COPY INTO. No transformations.';

CREATE SCHEMA IF NOT EXISTS BRONZE
    COMMENT = 'Light standardization — casting, normalization, source metadata preserved.';

CREATE SCHEMA IF NOT EXISTS SILVER
    COMMENT = 'Trusted canonical models — deduplication, FX normalization, SCD2.';

CREATE SCHEMA IF NOT EXISTS GOLD
    COMMENT = 'Analytics-ready star schema — fact tables, dimension tables, mart views.';

CREATE SCHEMA IF NOT EXISTS AUDIT
    COMMENT = 'Pipeline operational metadata — run logs, watermarks, reconciliation.';

CREATE SCHEMA IF NOT EXISTS SECURITY
    COMMENT = 'Dynamic data masking policies, secure views, PII governance.';

-- ────────────────────────────────────────
-- WAREHOUSES
-- ────────────────────────────────────────
CREATE WAREHOUSE IF NOT EXISTS FINANCE_INGEST_WH
    WAREHOUSE_SIZE   = 'X-SMALL'
    AUTO_SUSPEND     = 60
    AUTO_RESUME      = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Used for COPY INTO raw tables. Auto-suspends after 60s.';

CREATE WAREHOUSE IF NOT EXISTS FINANCE_TRANSFORM_WH
    WAREHOUSE_SIZE   = 'SMALL'
    AUTO_SUSPEND     = 120
    AUTO_RESUME      = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Used by dbt Bronze/Silver/Gold model runs.';

CREATE WAREHOUSE IF NOT EXISTS FINANCE_ANALYST_WH
    WAREHOUSE_SIZE   = 'SMALL'
    AUTO_SUSPEND     = 300
    AUTO_RESUME      = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Finance team analyst queries on Gold layer only.';

CREATE WAREHOUSE IF NOT EXISTS FINANCE_REPORTING_WH
    WAREHOUSE_SIZE   = 'X-SMALL'
    AUTO_SUSPEND     = 60
    AUTO_RESUME      = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Power BI / Streamlit dashboard queries.';

-- ────────────────────────────────────────
-- ROLES
-- ────────────────────────────────────────
CREATE ROLE IF NOT EXISTS FINANCE_LOADER
    COMMENT = 'Loads raw files via COPY INTO. RAW schema only.';

CREATE ROLE IF NOT EXISTS FINANCE_TRANSFORMER
    COMMENT = 'Runs dbt models. Access to all schemas for building.';

CREATE ROLE IF NOT EXISTS FINANCE_ANALYST
    COMMENT = 'Read-only on GOLD secure views. PII masked.';

CREATE ROLE IF NOT EXISTS FINANCE_AUDITOR
    COMMENT = 'Read GOLD + AUDIT for compliance review.';

CREATE ROLE IF NOT EXISTS FINANCE_ADMIN
    COMMENT = 'Full admin — infrastructure, RBAC, masking policies.';

-- Role hierarchy
GRANT ROLE FINANCE_LOADER      TO ROLE FINANCE_TRANSFORMER;
GRANT ROLE FINANCE_TRANSFORMER TO ROLE FINANCE_ADMIN;
GRANT ROLE FINANCE_ANALYST     TO ROLE FINANCE_ADMIN;
GRANT ROLE FINANCE_AUDITOR     TO ROLE FINANCE_ADMIN;
GRANT ROLE FINANCE_ADMIN       TO ROLE SYSADMIN;

-- ────────────────────────────────────────
-- WAREHOUSE GRANTS
-- ────────────────────────────────────────
GRANT USAGE ON WAREHOUSE FINANCE_INGEST_WH    TO ROLE FINANCE_LOADER;
GRANT USAGE ON WAREHOUSE FINANCE_TRANSFORM_WH TO ROLE FINANCE_TRANSFORMER;
GRANT USAGE ON WAREHOUSE FINANCE_ANALYST_WH   TO ROLE FINANCE_ANALYST;
GRANT USAGE ON WAREHOUSE FINANCE_ANALYST_WH   TO ROLE FINANCE_AUDITOR;
GRANT USAGE ON WAREHOUSE FINANCE_REPORTING_WH TO ROLE FINANCE_ANALYST;

-- ────────────────────────────────────────
-- DATABASE & SCHEMA GRANTS
-- ────────────────────────────────────────
GRANT USAGE ON DATABASE FINANCE_PLATFORM_DEV TO ROLE FINANCE_LOADER;
GRANT USAGE ON DATABASE FINANCE_PLATFORM_DEV TO ROLE FINANCE_TRANSFORMER;
GRANT USAGE ON DATABASE FINANCE_PLATFORM_DEV TO ROLE FINANCE_ANALYST;
GRANT USAGE ON DATABASE FINANCE_PLATFORM_DEV TO ROLE FINANCE_AUDITOR;

-- LOADER: RAW only
GRANT USAGE ON SCHEMA FINANCE_PLATFORM_DEV.RAW TO ROLE FINANCE_LOADER;
GRANT CREATE TABLE, INSERT, SELECT ON SCHEMA FINANCE_PLATFORM_DEV.RAW TO ROLE FINANCE_LOADER;

-- TRANSFORMER: all schemas
GRANT USAGE ON SCHEMA FINANCE_PLATFORM_DEV.RAW    TO ROLE FINANCE_TRANSFORMER;
GRANT USAGE ON SCHEMA FINANCE_PLATFORM_DEV.BRONZE  TO ROLE FINANCE_TRANSFORMER;
GRANT USAGE ON SCHEMA FINANCE_PLATFORM_DEV.SILVER  TO ROLE FINANCE_TRANSFORMER;
GRANT USAGE ON SCHEMA FINANCE_PLATFORM_DEV.GOLD    TO ROLE FINANCE_TRANSFORMER;
GRANT USAGE ON SCHEMA FINANCE_PLATFORM_DEV.AUDIT   TO ROLE FINANCE_TRANSFORMER;
GRANT ALL PRIVILEGES ON SCHEMA FINANCE_PLATFORM_DEV.BRONZE TO ROLE FINANCE_TRANSFORMER;
GRANT ALL PRIVILEGES ON SCHEMA FINANCE_PLATFORM_DEV.SILVER TO ROLE FINANCE_TRANSFORMER;
GRANT ALL PRIVILEGES ON SCHEMA FINANCE_PLATFORM_DEV.GOLD   TO ROLE FINANCE_TRANSFORMER;
GRANT ALL PRIVILEGES ON SCHEMA FINANCE_PLATFORM_DEV.AUDIT  TO ROLE FINANCE_TRANSFORMER;

-- ANALYST: GOLD only (read)
GRANT USAGE ON SCHEMA FINANCE_PLATFORM_DEV.GOLD TO ROLE FINANCE_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA FINANCE_PLATFORM_DEV.GOLD TO ROLE FINANCE_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FINANCE_PLATFORM_DEV.GOLD TO ROLE FINANCE_ANALYST;

-- AUDITOR: GOLD + AUDIT (read)
GRANT USAGE ON SCHEMA FINANCE_PLATFORM_DEV.GOLD  TO ROLE FINANCE_AUDITOR;
GRANT USAGE ON SCHEMA FINANCE_PLATFORM_DEV.AUDIT TO ROLE FINANCE_AUDITOR;
GRANT SELECT ON ALL TABLES IN SCHEMA FINANCE_PLATFORM_DEV.GOLD  TO ROLE FINANCE_AUDITOR;
GRANT SELECT ON ALL TABLES IN SCHEMA FINANCE_PLATFORM_DEV.AUDIT TO ROLE FINANCE_AUDITOR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FINANCE_PLATFORM_DEV.GOLD  TO ROLE FINANCE_AUDITOR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FINANCE_PLATFORM_DEV.AUDIT TO ROLE FINANCE_AUDITOR;

-- ────────────────────────────────────────
-- SERVICE USERS
-- (Replace passwords before running in prod)
-- ────────────────────────────────────────
CREATE USER IF NOT EXISTS FINANCE_DBT_USER
    PASSWORD            = 'ChangeMe_dbt_2024!'
    DEFAULT_ROLE        = FINANCE_TRANSFORMER
    DEFAULT_WAREHOUSE   = FINANCE_TRANSFORM_WH
    DEFAULT_NAMESPACE   = FINANCE_PLATFORM_DEV
    COMMENT             = 'Service account for dbt transformations';

CREATE USER IF NOT EXISTS FINANCE_AIRFLOW_USER
    PASSWORD            = 'ChangeMe_airflow_2024!'
    DEFAULT_ROLE        = FINANCE_LOADER
    DEFAULT_WAREHOUSE   = FINANCE_INGEST_WH
    DEFAULT_NAMESPACE   = FINANCE_PLATFORM_DEV
    COMMENT             = 'Service account for Airflow Snowflake operator';

GRANT ROLE FINANCE_TRANSFORMER TO USER FINANCE_DBT_USER;
GRANT ROLE FINANCE_LOADER      TO USER FINANCE_AIRFLOW_USER;
GRANT ROLE FINANCE_TRANSFORMER TO USER FINANCE_AIRFLOW_USER;

SELECT 'Script 01 complete — schemas, warehouses, roles created.' AS STATUS;
